name: notification
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2

  # state management
  flutter_riverpod: ^1.0.3

  # notifications
  flutter_apns: ^1.5.4
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets
